name: MLflow CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
      
      - name: Check Env
        run: |
          echo "Checking environment..."
          python --version
          pip --version
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run MLflow Project
        run: |
          cd MLProject
           python modelling.py
          echo "MLflow project completed"
      
      - name: Get latest MLflow run id
        run: |
          cd MLProject
          echo "Getting latest MLflow run information..."
          python -c "
          import mlflow
          import os
          if os.path.exists('mlruns'):
              print('MLflow artifacts generated')
              print('MLruns directory contents:')
              os.system('find mlruns -name \"*.json\" | head -5')
              
              # Try to get the latest run ID
              try:
                  experiments = mlflow.search_experiments()
                  if experiments:
                      runs = mlflow.search_runs(experiment_ids=[experiments[0].experiment_id])
                      if not runs.empty:
                          latest_run_id = runs.iloc[0]['run_id']
                          print(f'Latest Run ID: {latest_run_id}')
                      else:
                          print('No runs found')
                  else:
                      print('No experiments found')
              except Exception as e:
                  print(f'Could not retrieve run info: {e}')
          else:
              print('No mlruns directory found')
          "
          echo "Workflow completed successfully!"